### ISSUE TITLE
Tramp changes seems to have broken the functionality

### ISSUE THREAD

**Issue by swarnendubiswas** [nflath/sudo-edit#3] opened 2016-06-25 14:33 UTC
After the recent update, I face the following error: `tramp-file-name-handler: Host ‘XXX’ looks like a remote host, ‘sudo’ can only use the local host`. Note that `XXX` is the `tramp-default-host` that I have initialized.

**Comment by nflath** [comment] 2016-06-25 16:42
Thanks for the report! I've reverted the merge for now.

**Comment by marsam** [comment] 2016-06-25 20:57
Hi:
This happens because multihop support uses `tramp-default-proxies-alist` [underneath](https://stackoverflow.com/a/16408592), so some command is saving the proxy: `/sudo:root@remotehost:/path/to/file` for future sessions, and after a Emacs restart `tramp-default-proxies-alist` is `nil` and so throws that error.

I'm roughly guessing [projectile](https://github.com/bbatsov/projectile) saved the proxy in `projectile-known-projects`; if so you can disable projectile to save remote directories:

``` elisp
(setq projectile-ignored-project-function 'file-remote-p)
```

or disabling only for projects with `/sudo:`:

``` elisp
(defun marsam/projectile-ignore-sudo-projects (file-name)
  "Return non-nil if FILE-NAME is opened with tramp sudo."
  (and (file-remote-p file-name) (string-match-p "\\`/sudo:" file-name)))

(setq projectile-ignored-project-function 'marsam/projectile-ignore-sudo)
```

@swarnendubiswas which command triggered the error?

**Comment by swarnendubiswas** [comment] 2016-06-25 21:30
@marsam `sudo-edit`.

**Comment by marsam** [comment] 2016-06-25 23:13
I'm sorry, I can't reproduce this.

**Comment by swarnendubiswas** [comment] 2016-06-27 13:04
I have attached a snippet. Start with `emacs -Q` and evaluate the snippet.

```
(require 'package)
(setq package-user-dir (expand-file-name "~/.emacs.d/elpa/")
      package-enable-at-startup nil)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(use-package tramp ; /method:user@host#port:filename. Shortcut /ssh:: will connect to default user@host#port.
  :defer t
  :config
  (setq tramp-default-method "ssh" ; ssh is faster than the default scp
        tramp-default-user "xxx"
        tramp-default-host "yyy"))

(use-package sudo-edit ; Edit file with sudo
  :ensure t
  :bind ("M-s e" . sudo-edit))
```

I face the error while editing a root file with `sudo-edit`.

**Comment by articuluxe** [comment] 2016-08-23 17:59
I can reproduce this error editing a root file while connected via tramp to a remote host, on the latest version of sudo-edit, after the tramp enhancement was reverted.  But re-enabling the tramp enhancement, I cannot reproduce (I don't use projectile, if that has any impact).

@swarnendubiswas Just a thought, is it possible you had used /sudo:: to edit a file on a remote host, which is causing that default host to be stored?

In any event, my question is: Is there any way the tramp enhancement can be merged again?  Perhaps a customization setting could permit users to enable or disable it at will.

Although I'm not clear why you took away sudo-edit-current-file, I find a separate command more convenient, but that's just me.

One issue I did have with the new tramp code is that for some reason I was connected to the remote file via scp, not ssh.  So sudo-edit failed because scp cannot be used in multi-hop syntax.  I wonder if the remote method is scp, that it should be forced to ssh when doing sudo-edit, as it won't ever succeed with scp.

**Comment by swarnendubiswas** [comment] 2016-08-24 04:14
@danrharms My issue was while editing local files which required root access.

**Comment by nflath** [comment] 2016-08-29 05:34
@danrharms I'd be fine with putting it behind a config option.
@marsam Have you tried the reproduction?

**Comment by marsam** [comment] 2016-08-29 23:31
Sorry, I could not reproduce this issue. My only guess is that the initial version of my patch relied on the default parameters of `/sudo`  as [`/sudo::/path/to/file`](https://github.com/nflath/sudo-edit/blob/1dd89f6/sudo-edit-test.el#L40-L41), instead of espeficing the user (`root`) and host (`localhost`); which caused problems in some tramp versions.

I've made another patch in #6, which is [backwards compatible](https://github.com/nflath/sudo-edit/blob/f4fcb63/sudo-edit-test.el#L41-L43).

@swarnendubiswas, @danrharms  can you please test #6

**Comment by swarnendubiswas** [comment] 2016-08-30 15:25
@marsam I am testing your recent patch, will update in a few days.

**Comment by articuluxe** [comment] 2016-08-31 13:06
Looks good to me so far. 

The only issue I've encountered is what I mentioned before. Tramp throws an error when multi-hop syntax uses the scp method. Even when scp is used to open the remote file, when sudo-edit uses multi-hop syntax in order to open as root, I think it should force scp to ssh. 

Should I open a separate issue for this?

**Comment by nflath** [comment] 2016-08-31 15:51
@danrharms yes, please.

**Comment by nflath** [comment] 2016-09-05 06:21
@swarnendubiswas  Any update on the testing?

**Comment by swarnendubiswas** [comment] 2016-09-05 17:00
@nflath @marsam I tested the patch, and it works. I did not reply immediately because I faced performance issues. It seems Emacs and the editing process becomes very slow with `sudo-edit`. I am not sure what could this be related to, and whether they are even related to the tramp changes.

**Comment by marsam** [comment] 2016-09-05 20:29
@swarnendubiswas I think the performace issues are unrelated to `sudo-edit`. `sudo-edit` only creates the filename the posterior file manipulations are handled by Emacs itself.

**Comment by swarnendubiswas** [comment] 2016-09-05 20:56
Okay then.

**Comment by nflath** [comment] 2016-09-06 04:53
Merged.  Thanks!

**Closed as completed by nflath** 2016-09-06 04:53 UTC
